{
 "title": "Global Dashboard",
 "description": "This dashboard offers a global overview of the Infrabox structure. It should contains every important information.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Basic Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Project Count",
   "type": "singlestat",
   "description": "The total number of projects registered in the database.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "rawSql": "SELECT count(id)\nFROM project" }
   ]
  },
  {
   "title": "Cluster Count",
   "type": "singlestat",
   "description": "The total number of clusters registered in the database.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(name)\nFROM cluster"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "singlestat",
   "description": "The total number of cluster's nodes registered in the database.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM(nodes)\nFROM cluster"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "singlestat",
   "description": "The total number of users registered in the database. Does include the root user.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(id)\nfrom public.user"
    }
   ]
  },
  {
   "title": "Cluster Overview",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT c.name, c.nodes, count(j.id) filter (WHERE j.state = 'running') as running,\n  count(j.id) filter (WHERE j.state = 'scheduled') as scheduled,\n  count(j.id) filter (WHERE j.state = 'queued') as queued,\n  (sum(j.cpu) FILTER (WHERE j.state = 'running' ))::float / c.cpu_capacity as cpu_use, \n  (sum(j.memory) filter (WHERE j.state = 'running'))::float / c.memory_capacity * 1024 as mem_use\nFROM cluster c LEFT OUTER JOIN job j\nON c.name = j.cluster_name\nGROUP BY c.name"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "graph",
   "description": "Amount of jobs of different states over time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "sum(job_current_count) by(state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Ressources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Memory use - Over time",
   "type": "graph",
   "description": "Total amount of allocated memory by running jobs among all clusters.",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rsc_current_count{cluster=\"'%'\", rsc=\"mem\"})",
     "legendFormat": "Memory allocation",
     "rawSql": "SELECT to_timestamp(foo.time) as time, sum(mem) as mem FROM(\n\nSELECT\n  $__timeGroup(start_date,'30s'),\n  sum(memory) as mem\nFROM job\nWHERE (start_date, end_date) OVERLAPS ($__timeFrom(), $__timeTo()) AND cluster_name LIKE [[cluster]] and start_date is not null and end_date is not null\nGROUP BY time\nunion all\nSELECT\n  $__timeGroup(end_date,'30s'),\n  sum(memory) as mem\nFROM job\nWHERE (start_date, end_date) OVERLAPS ($__timeFrom(), $__timeTo()) AND cluster_name LIKE [[cluster]] and start_date is not null and end_date is not null\nGROUP BY time\n) as foo GROUP by to_timestamp(foo.time) ORDER by to_timestamp(foo.time)\n"
    }
   ]
  },
  {
   "title": "Memory use - Current",
   "type": "singlestat",
   "description": "Ratio of current running job's allocated memory among the sum of very cluster's capacity.",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 14 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(j.memory)::float*100 / (SELECT sum(memory_capacity)/1024 FROM cluster) as percentage\nFROM job j\nWHERE j.state = 'running'"
    }
   ]
  },
  {
   "title": "Memory capacity",
   "type": "singlestat",
   "description": "Total memory capacity of the clusters.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 14 },
   "format": "deckbytes",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(memory_capacity)\nFROM cluster\n"
    }
   ]
  },
  {
   "title": "CPU use - Over time",
   "type": "graph",
   "description": "Total amount of allocated cores by running jobs among all clusters.",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rsc_current_count{cluster=\"'%'\", rsc=\"cpu\"})",
     "legendFormat": "Allocated cores",
     "rawSql": "SELECT to_timestamp(foo.time) as time, sum(cpu) as cpu FROM(\n\nSELECT\n  $__timeGroup(start_date,'30s'),\n  sum(cpu) as cpu\nFROM job\nWHERE (start_date, end_date) OVERLAPS ($__timeFrom(), $__timeTo()) AND cluster_name LIKE [[cluster]] and start_date is not null and end_date is not null\nGROUP BY time\nunion all\nSELECT\n  $__timeGroup(end_date,'30s'),\n  sum(cpu) as cpu\nFROM job\nWHERE (start_date, end_date) OVERLAPS ($__timeFrom(), $__timeTo()) AND cluster_name LIKE [[cluster]] and start_date is not null and end_date is not null\nGROUP BY time\n) as foo GROUP by to_timestamp(foo.time) ORDER by to_timestamp(foo.time)\n"
    }
   ]
  },
  {
   "title": "CPU use - Current",
   "type": "singlestat",
   "description": "Ratio of current running job's allocated CPU cores among the sum of every cluster's capacity.",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 19 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(j.cpu)::float*100 / (SELECT sum(cpu_capacity) FROM cluster ) as percentage\nFROM job j\nWHERE j.state = 'running'"
    }
   ]
  },
  {
   "title": "CPU capacity",
   "type": "singlestat",
   "description": "Total CPU capacity of the clusters.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 19 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(cpu_capacity)\nFROM cluster"
    }
   ]
  }
 ]
}