{
 "title": "Node Inspector",
 "description": "Allows to inspect the health of a Node. The ressources Graph are inspired by the Node Inspector Full ones.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "Node",
    "query": "select distinct node_name from job"
   }
  ]
 },
 "panels": [
  { "title": "Jobs Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job count",
   "type": "graph",
   "description": "Count of the jobs assigned to the inspected node.",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job_all_node_count{node=\"$node_name\"}",
     "legendFormat": "{{state}}",
     "rawSql": "job_all_node_count{node=\"$node_name\"}\n"
    }
   ]
  },
  {
   "title": "Unexpected Termination",
   "type": "graph",
   "description": "Display end times of FAILURE / ERROR / KILLED job of the inspected node, over the time range.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(end_date),\n  count(id) as Killed\nFROM\n  job\nWHERE\n  $__timeFilter(end_date)\n  AND state = 'killed'\n  AND node_name = '[[node_name]]'\nGROUP BY\n  time"
    },
    {
     "rawSql": "SELECT\n  $__time(end_date),\n  count(id) as Failure\nFROM\n  job\nWHERE\n  $__timeFilter(end_date)\n  AND state = 'failure'\n  AND node_name = '[[node_name]]'\nGROUP BY\n  time"
    },
    {
     "rawSql": "SELECT\n  $__time(end_date),\n  coalesce(count(id),0) as Error\nFROM\n  job\nWHERE\n  $__timeFilter(end_date)\n  AND state = 'error'\n  AND node_name = '[[node_name]]'\nGROUP BY\n time"
    }
   ]
  },
  { "title": "Ressources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Rate over the last two points of the CPU usage.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\"}[5m]) * on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)) * 100",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user'}[5m])* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice'}[5m])* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)) * 100",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle'}[5m])* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)) * 100",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait'}[5m])* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)) * 100",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq'}[5m])* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)) * 100",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq'}[5m])* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)) * 100",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal'}[5m])* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)) * 100",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest'}[5m])* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)) * 100",
     "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes  * on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "(node_memory_MemTotal_bytes* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n))\n- (node_memory_MemFree_bytes* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)) \n- ((node_memory_Cached_bytes* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)) + node_memory_Buffers_bytes* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n))",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "(node_memory_Cached_bytes* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)) + (node_memory_Buffers_bytes* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n))",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "((node_memory_SwapTotal_bytes* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)) - (node_memory_SwapFree_bytes* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)))",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "Rate over the last two values of the network traffic over time.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[5m])* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[5m]) * on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n)) - (node_filesystem_avail_bytes* on(instance) group_left(nodename)\n(\nnode_uname_info{nodename=\"$node_name\"}\n))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}