FROM alpine:3.4

RUN apk add --no-cache \
    python  \
    curl \
    bash \
    py-requests \
    py-psycopg2 \
    py-nose \
    py-flask \
    postgresql-client && \
    rm -rf /var/cache/apk/*

ENV HOME /
RUN curl https://sdk.cloud.google.com | bash

ENV PATH /google-cloud-sdk/bin:$PATH
