-- Non-contiguous migration fixture.
--
-- Numbers 00051..00059 are intentionally missing so this file exercises the
-- gap-tolerant selection logic added in the first commit of DM01-6184
-- (SAP/InfraBox#636):  get_files() now filters by file number
-- (`int(f[:5]) > current_schema_version`) instead of slicing the sorted list
-- with the index, so a gap of any size no longer causes later migrations to
-- be skipped or re-run.
--
-- The statement below is intentionally trivial (no schema change), so
-- apply_migration is expected to run it via psycopg2 without side effects
-- and still advance schema_version to 60.
SELECT 1;