// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gardener/gardener/pkg/client/gardener/clientset/versioned/typed/gardener/v1beta1 (interfaces: CloudProfileInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	v1beta1 "github.com/gardener/gardener/pkg/apis/garden/v1beta1"
	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	reflect "reflect"
)

// MockCloudProfileInterface is a mock of CloudProfileInterface interface
type MockCloudProfileInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCloudProfileInterfaceMockRecorder
}

// MockCloudProfileInterfaceMockRecorder is the mock recorder for MockCloudProfileInterface
type MockCloudProfileInterfaceMockRecorder struct {
	mock *MockCloudProfileInterface
}

// NewMockCloudProfileInterface creates a new mock instance
func NewMockCloudProfileInterface(ctrl *gomock.Controller) *MockCloudProfileInterface {
	mock := &MockCloudProfileInterface{ctrl: ctrl}
	mock.recorder = &MockCloudProfileInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCloudProfileInterface) EXPECT() *MockCloudProfileInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockCloudProfileInterface) Create(arg0 *v1beta1.CloudProfile) (*v1beta1.CloudProfile, error) {
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*v1beta1.CloudProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockCloudProfileInterfaceMockRecorder) Create(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCloudProfileInterface)(nil).Create), arg0)
}

// Delete mocks base method
func (m *MockCloudProfileInterface) Delete(arg0 string, arg1 *v1.DeleteOptions) error {
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockCloudProfileInterfaceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCloudProfileInterface)(nil).Delete), arg0, arg1)
}

// DeleteCollection mocks base method
func (m *MockCloudProfileInterface) DeleteCollection(arg0 *v1.DeleteOptions, arg1 v1.ListOptions) error {
	ret := m.ctrl.Call(m, "DeleteCollection", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCollection indicates an expected call of DeleteCollection
func (mr *MockCloudProfileInterfaceMockRecorder) DeleteCollection(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollection", reflect.TypeOf((*MockCloudProfileInterface)(nil).DeleteCollection), arg0, arg1)
}

// Get mocks base method
func (m *MockCloudProfileInterface) Get(arg0 string, arg1 v1.GetOptions) (*v1beta1.CloudProfile, error) {
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*v1beta1.CloudProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockCloudProfileInterfaceMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCloudProfileInterface)(nil).Get), arg0, arg1)
}

// List mocks base method
func (m *MockCloudProfileInterface) List(arg0 v1.ListOptions) (*v1beta1.CloudProfileList, error) {
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].(*v1beta1.CloudProfileList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockCloudProfileInterfaceMockRecorder) List(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCloudProfileInterface)(nil).List), arg0)
}

// Patch mocks base method
func (m *MockCloudProfileInterface) Patch(arg0 string, arg1 types.PatchType, arg2 []byte, arg3 ...string) (*v1beta1.CloudProfile, error) {
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Patch", varargs...)
	ret0, _ := ret[0].(*v1beta1.CloudProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch
func (mr *MockCloudProfileInterfaceMockRecorder) Patch(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockCloudProfileInterface)(nil).Patch), varargs...)
}

// Update mocks base method
func (m *MockCloudProfileInterface) Update(arg0 *v1beta1.CloudProfile) (*v1beta1.CloudProfile, error) {
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(*v1beta1.CloudProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockCloudProfileInterfaceMockRecorder) Update(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCloudProfileInterface)(nil).Update), arg0)
}

// Watch mocks base method
func (m *MockCloudProfileInterface) Watch(arg0 v1.ListOptions) (watch.Interface, error) {
	ret := m.ctrl.Call(m, "Watch", arg0)
	ret0, _ := ret[0].(watch.Interface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Watch indicates an expected call of Watch
func (mr *MockCloudProfileInterfaceMockRecorder) Watch(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockCloudProfileInterface)(nil).Watch), arg0)
}
