apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: infrabox-gc
    namespace: {{ template "system_namespace" . }}
    labels:
        app: infrabox-gc
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: infrabox-gc
        spec:
            {{ include "imagePullSecret" . | indent 8 }}
            terminationGracePeriodSeconds: 0
            serviceAccountName: infrabox
            containers:
            {{ include "containers_database" . | indent 12 }}
            -
                name: gc
                image: {{ include "image_repository" . }}/gc:{{ include "image_tag" . }}
                env:
                {{ include "env_database" . | indent 16 }}
                {{ include "env_general" . | indent 16 }}
                {{ include "env_version" . | indent 16 }}
                {{ include "env_gcs" . | indent 16 }}
                {{ include "env_s3" . | indent 16 }}
                {{ include "env_azure" . | indent 16 }}
                {{ include "env_swift" . | indent 16 }}
            volumes:
                {{ include "volumes_database" . | indent 16 }}