{{ if .Values.network_policies.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-all-in-system-namespaces
  namespace: {{ template "system_namespace" . }}
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          infrabox: system
{{ end }}