[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.3"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  branch = "master"
  # version = "=v0.0.5"

[[constraint]]
  name = "github.com/gardener/gardener"
  version = "0.10.2"

[[constraint]]
  name = "github.com/evanphx/json-patch"
  version = "v3.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.2.2"
