{
 "title": "Cluster Inspector",
 "description": "This dashboard offers a more specific overview of each cluster.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Inspected Cluster",
    "query": "select distinct name from cluster"
   }
  ]
 },
 "panels": [
  { "title": "Basic Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected nodes",
   "type": "singlestat",
   "description": "The number of nodes connected to the inspected cluster.",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT nodes FROM cluster WHERE name = '[[cluster]]'"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "graph",
   "description": "Amount of jobs of different states over time among the inspected cluster.",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "job_current_count{cluster='[[cluster]]'}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Ressources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory use - Over time",
   "type": "graph",
   "description": "Total amount of allocated memory by running jobs among the inspected cluster.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rsc_current_count{cluster=\"[[cluster]]\", rsc=\"mem\"}) by(rsc)",
     "legendFormat": "Memory allocation",
     "rawSql": "SELECT to_timestamp(foo.time) as time, sum(mem) as mem FROM(\n\nSELECT\n  $__timeGroup(start_date,'30s'),\n  sum(memory) as mem\nFROM job\nWHERE (start_date, end_date) OVERLAPS ($__timeFrom(), $__timeTo()) AND cluster_name LIKE [[cluster]] and start_date is not null and end_date is not null\nGROUP BY time\nunion all\nSELECT\n  $__timeGroup(end_date,'30s'),\n  sum(memory) as mem\nFROM job\nWHERE (start_date, end_date) OVERLAPS ($__timeFrom(), $__timeTo()) AND cluster_name LIKE [[cluster]] and start_date is not null and end_date is not null\nGROUP BY time\n) as foo GROUP by to_timestamp(foo.time) ORDER by to_timestamp(foo.time)\n"
    }
   ]
  },
  {
   "title": "Memory use - Current",
   "type": "singlestat",
   "description": "Ratio of current running job's allocated memory among the inspected cluster capacity.",
   "gridPos": { "h": 7, "w": 3, "x": 16, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(j.memory)::float*100 / (SELECT memory_capacity/1024 FROM cluster WHERE name ='[[cluster]]') as percentage\nFROM job j\nWHERE j.cluster_name = '[[cluster]]' AND j.state = 'running'"
    }
   ]
  },
  {
   "title": "Memory capacity",
   "type": "singlestat",
   "description": "Memory capacity of the inspected cluster.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 9 },
   "format": "deckbytes",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT memory_capacity\nFROM cluster\nWHERE name = '[[cluster]]'\n"
    }
   ]
  },
  {
   "title": "CPU use - Over time",
   "type": "graph",
   "description": "Total amount of allocated CPU cores for all running jobs of the inspected cluster.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rsc_current_count{cluster=\"[[cluster]]\", rsc=\"cpu\"}) by(rsc)",
     "legendFormat": "Allocated cores",
     "rawSql": "SELECT to_timestamp(foo.time) as time, sum(cpu) as cpu FROM(\n\nSELECT\n  $__timeGroup(start_date,'30s'),\n  sum(cpu) as cpu\nFROM job\nWHERE (start_date, end_date) OVERLAPS ($__timeFrom(), $__timeTo()) AND cluster_name LIKE [[cluster]] and start_date is not null and end_date is not null\nGROUP BY time\nunion all\nSELECT\n  $__timeGroup(end_date,'30s'),\n  sum(cpu) as cpu\nFROM job\nWHERE (start_date, end_date) OVERLAPS ($__timeFrom(), $__timeTo()) AND cluster_name LIKE [[cluster]] and start_date is not null and end_date is not null\nGROUP BY time\n) as foo GROUP by to_timestamp(foo.time) ORDER by to_timestamp(foo.time)\n"
    }
   ]
  },
  {
   "title": "CPU use - Current",
   "type": "singlestat",
   "description": "Ratio of current running job's allocated CPU cores among the inspected cluster capacity.",
   "gridPos": { "h": 7, "w": 3, "x": 16, "y": 16 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(j.cpu)::float*100 / (SELECT cpu_capacity FROM cluster WHERE name = '[[cluster]]') as percentage\nFROM job j\nWHERE j.cluster_name = '[[cluster]]' AND j.state = 'running'"
    }
   ]
  },
  {
   "title": "CPU capacity",
   "type": "singlestat",
   "description": "CPU cores capacity of the inspected cluster.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 16 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT cpu_capacity\nFROM cluster\nWHERE name = '[[cluster]]'\n"
    }
   ]
  }
 ]
}