{
 "title": "Job Inspector",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "id",
    "query": "7ee5fa36-deca-4e32-9cb8-a8ee64ca92db"
   }
  ]
 },
 "panels": [
  {
   "title": "General Information",
   "type": "table",
   "description": "Some general informations about the inspected job. This page is not intended to be accessed directly but through the Build Inspector dashboard, in order to properly set the job identifier.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT p.name as p_name, b.build_number, b.restart_counter, j.name as j_name, j.cpu, j.memory, c.cpu_capacity, c.memory_capacity, j.id\nFROM project p, build b, job j, cluster c\nWHERE p.id = j.project_id AND b.id = j.build_id AND c.name = j.cluster_name AND j.id = '[[id]]'"
    }
   ]
  },
  {
   "title": "Memory use",
   "type": "graph",
   "description": "Graphical representation of the used memory as registered in the database.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory use" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(date),\n  mem::float as used,\n  mem_j_limit as job_limit\nFROM (\n  select to_timestamp((elm::jsonb->'date')::text::int) as date, elm::jsonb->>'mem'::text as mem, mem_j_limit from (\n    select\n      jsonb_array_elements(j.stats::jsonb->'[[id]]') as elm, j.memory as mem_j_limit\n    FROM\n      job j\n    WHERE \n      j.id = '[[id]]'\n    ) as foo2 order by date asc\n) as foo\n  \n\n"
    }
   ]
  },
  {
   "title": "CPU  use",
   "type": "graph",
   "description": "Graphical representation of the CPU frequency of the job as registered in the database.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(date),\n  cpu::float*1024 as cpu\nFROM (\n  select to_timestamp((elm::jsonb->'date')::text::int) as date, elm::jsonb->>'cpu'::text as cpu from (\n    select\n      jsonb_array_elements(j.stats::jsonb->'[[id]]') as elm\n    FROM\n      job j\n    WHERE \n      j.id = '[[id]]'\n    ) as foo2 order by date asc\n) as foo\n  \n\n"
    }
   ]
  },
  {
   "title": "MESSAGE",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select message from job where id = '[[id]]'"
    }
   ]
  }
 ]
}