{
 "title": "Project Inspector Copy",
 "description": "This dashboard offers a more detailed inspection of the selected project.",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pname",
    "label": "Project Name",
    "query": "select distinct name from project order by name"
   },
   { "name": "cluster", "label": "Inspected cluster", "query": "select name from cluster" }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Project Informations",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "Select '[[pname]]' as name, p.id as id, p.public as public, p.build_on_push as build_on_push, p.build_on_trigger as build_on_trigger, count(c.user_id)\nfrom project p LEFT OUTER JOIN collaborator c\nON  c.project_id = p.id\nWHERE name = '[[pname]]'\nGROUP BY id",
     "target": "project_inspector_information",
     "type": "table"
    }
   ]
  },
  {
   "title": "Jobs Success Rate (TR)",
   "type": "singlestat",
   "description": "Success rate for all the jobs of the project.\n\n(TR) means that the data is computed only for  jobs which end date are in the specified time range. The default time range is the last week",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(builds_over_time_range)",
     "rawSql": "SELECT \n  CASE\n\t  count(j.id) filter (where j.state NOT IN ('running', 'scheduled', 'queued'))\n  WHEN\n\t  0\n  THEN\n\t\tNULL\n  ELSE \n\t\t(count(j.id) filter (where j.state = 'finished'))::float / (count(j.id) filter (where j.state NOT IN ('running', 'scheduled', 'queued')))::float\n  END as success_rate_7d\nFROM job j\nWHERE $__timeFilter(j.end_date) AND j.project_id = (select id from project where name = '[[pname]]')",
     "target": "Jobs_Success_Rate",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "AVG Build Success Rate (TR)",
   "type": "singlestat",
   "description": "Average of the Success Rate of each build of the project.\n\n(TR) means that the data is computed only for  jobs which end date are in the specified time range. The default time range is the last week",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT AVG(foo.success_rate_7d) FROM (\nSELECT \n  CASE\n\t  count(j.id) filter (where j.state NOT IN ('running', 'scheduled', 'queued'))\n  WHEN\n\t  0\n  THEN\n\t\tNULL\n  ELSE \n\t\t(count(j.id) filter (where j.state = 'finished'))::float / (count(j.id) filter (where j.state NOT IN ('running', 'scheduled', 'queued')))::float\n  END as success_rate_7d\nFROM job j\nWHERE $__timeFilter(j.end_date) AND j.project_id = (select id from project where name = '[[pname]]')\nGROUP BY build_id) as foo",
     "target": "AVG_Build_Success_Rate",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Builds over time range (TR)",
   "type": "singlestat",
   "description": "The number of builds of this project which have jobs with their end date in the specified time range (TR).\nThe default time range is the last week",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(DISTINCT build_id)\nFROM job\nWHERE project_id = (select id from project where name = '[[pname]]') AND $__timeFilter(end_date) AND state NOT IN ('running', 'scheduled', 'queued')",
     "target": "Builds_Over_Time_Range",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Project's running jobs",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT c.name as cluster, count(j.id) as jobs\nFROM cluster c LEFT OUTER JOIN job j \nON j.state = 'running' ANd j.cluster_name = c.name AND j.project_id = (select id from project where name = '[[pname]]')\nGROUP BY c.name",
     "target": "projects_running_jobs",
     "type": "table"
    }
   ]
  },
  { "title": "Ressource use by this project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Cluster RAM use",
   "type": "singlestat",
   "description": "Proportion of the allocated memory for the running jobs of this project among the total cluster capacity.\n\n\nIf All clusters are inspected, we simply compute the sum.",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rsc_current_count{project=\"[[pname]]\", cluster=\"[[cluster]]\", rsc=\"mem\"})",
     "rawSql": "SELECT \tCASE (\n\t\tSELECT count(id)\n\t\tFROM job\n\t\tWHERE project_id = (select id from project where name = '[[pname]]') AND state = 'running' and cluster_name LIKE [[cluster]])\n\tWHEN 0 THEN 0\n\tELSE (\n\t\tSELECT DISTINCT SUM((j.definition#>>'{resources,limits,memory}')::float) / ((SELECT DISTINCT CASE [[cluster]] WHEN '%' THEN (SELECT sum(memory_capacity) from cluster) ELSE c.memory_capacity END)/1024)\n\t\tFROM job j, cluster c\n\t\tWHERE j.project_id = (select id from project where name = '[[pname]]') AND j.cluster_name LIKE [[cluster]] AND c.name LIKE [[cluster]] AND j.state = 'running'\n\t\tGROUP BY c.name\n\t)\nEND",
     "target": "select metric",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Cluster's memory use - Over time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 7 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rsc_current_count{project=\"[[pname]]\", cluster=\"[[cluster]]\", rsc=\"mem\"}",
     "legendFormat": "Allocated memory"
    }
   ]
  },
  {
   "title": "Cluster CPU use",
   "type": "singlestat",
   "description": "Proportion of the allocated cores for the running jobs of this project among the total cluster capacity.\n\n\nIf All clusters are inspected, we simply compute the sum.",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 12 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rsc_current_count{project=\"[[pname]]\", cluster=\"[[cluster]]\", rsc=\"cpu\"})",
     "rawSql": "SELECT \tCASE (\n\t\tSELECT count(id)\n\t\tFROM job\n\t\tWHERE project_id = (select id from project where name = '[[pname]]') AND state = 'running' and cluster_name LIKE [[cluster]])\n\tWHEN 0 THEN 0\n\tELSE (\n\t\tSELECT DISTINCT SUM((j.definition#>>'{resources,limits,cpu}')::float) / (SELECT DISTINCT CASE [[cluster]] WHEN '%' THEN (SELECT sum(cpu_capacity) from cluster) ELSE c.cpu_capacity END)\n\t\tFROM job j, cluster c\n\t\tWHERE j.project_id = (select id from project where name = '[[pname]]') AND j.cluster_name LIKE [[cluster]] AND c.name LIKE [[cluster]] AND j.state = 'running'\n\t\tGROUP BY c.name\n\t)\nEND"
    }
   ]
  },
  {
   "title": "Cluster's CPU use - Over time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rsc_current_count{project=\"[[pname]]\", cluster=\"[[cluster]]\", rsc=\"cpu\"}",
     "legendFormat": "Allocated cores",
     "rawSql": "rsc_current_count{project=\"[[pname]]\", cluster=\"[[cluster]]\", rsc=\"cpu\"}"
    }
   ]
  },
  { "title": "Builds Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Build List",
   "type": "table",
   "description": "List all the builds of this project.\n\n\nThe success rate is computed over a specific time range (TR) as the proportion of 'finished' jobs among ended jobs (ie : not queued, scheduled or running).\n\nThe default time range is the last week.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT pinfo.name as pname, b.build_number, b.restart_counter, sr.sr, b.id\nFROM  (SELECT id, build_number, restart_counter FROM build WHERE project_id = (select id from project where name = '[[pname]]')) b\nLEFT OUTER JOIN (SELECT build_id,\n  CASE\n\t  count(j.id) filter (where j.state NOT IN ('running', 'scheduled', 'queued'))\n  WHEN\n\t  0\n  THEN\n\t\tNULL\n  ELSE \n\t\t(count(j.id) filter (where j.state = 'finished'))::float / (count(j.id) filter (where j.state NOT IN ('running', 'scheduled', 'queued')))::float\n  END as sr\n  FROM job j\n  WHERE j.project_id = (select id from project where name = '[[pname]]') AND $__timeFilter(j.end_date)\n  GROUP BY build_id) sr\nON sr.build_id = bhttps://ha-eu-de-1.infrabox.datahub.only.sap/grafana/#.id\nLEFT JOIN (SELECT name FROM project WHERE  name = '[[pname]]') pinfo ON true\n",
     "target": "build_list",
     "type": "table"
    }
   ]
  }
 ]
}