{
 "title": "Projects Overview Copy",
 "description": "This dashboard offers a few informations about projects and a global overview for each of them",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Project Count",
   "type": "singlestat",
   "description": "Total amount of projects registered in the database",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(project_amount)", "rawSql": "SELECT COUNT(id) from project" }
   ]
  },
  {
   "title": "Detailed count",
   "type": "table",
   "description": "More detailed count of each kind of project",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "project_amount",
     "rawSql": "SELECT type, count(id)\nFROM project\nGROUP BY type",
     "target": "select metric",
     "type": "table"
    }
   ]
  },
  {
   "title": "Projects list",
   "type": "table",
   "description": "List all the projects of the database.\n\n(TR) means that the data is computed only for runnings jobs and jobs which end date are in the specified time range.\nThe default time range is the last week.\n\n\nCPU and RAM datas are the datas allocated for each job, not their actual consumption. CPU represents the number of cores.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \tp.name, p.type, p.public, \n\tj_infos.jobs_runnings as jobs_runnings,\n\tj_infos.failed_jobs_7d as failed_jobs_7d,\n\tj_infos.success_rate_7d as success_rate_7d,\n\tc_infos.collabs as collabs,\n\tj_infos.avg_cpu as avg_cpu,\n\tj_infos.min_cpu as min_cpu,\n\tj_infos.max_cpu as max_cpu,\n\tj_infos.avg_mem as avg_mem,\n\tj_infos.min_mem as min_mem,\n\tj_infos.max_mem as max_mem,\n\tp.id\nFROM project p LEFT OUTER JOIN \n(SELECT\n\tj.project_id,\n\tcount(j.id) filter (where j.state = 'running') as jobs_runnings,\n\tcount(j.id) filter (where (j.state IN ('failure', 'error')) and $__timeFilter(j.end_date)) as failed_jobs_7d,\n\tCASE\n\t  count(j.id) filter (where j.state NOT IN ('running', 'scheduled', 'queued') and $__timeFilter(j.end_date))\n\tWHEN\n\t  0\n\tTHEN\n\t\tNULL\n\tELSE \n\t\t(count(j.id) filter (where (j.state = 'finished' and $__timeFilter(j.end_date))))::float / (count(j.id) filter (where j.state NOT IN ('running', 'scheduled', 'queued') and $__timeFilter(j.end_date)))::float\n\tEND as success_rate_7d,\n\tavg((j.definition#>>'{resources,limits,cpu}')::float) filter (where $__timeFilter(j.end_date) OR j.state = 'running') as avg_cpu,\n\tmin((j.definition#>>'{resources,limits,cpu}')::float) filter (where $__timeFilter(j.end_date) OR j.state = 'running') as min_cpu,\n\tmax((j.definition#>>'{resources,limits,cpu}')::float) filter (where $__timeFilter(j.end_date) OR j.state = 'running') as max_cpu,\n\tavg((j.definition#>>'{resources,limits,memory}')::float) filter (where $__timeFilter(j.end_date) OR j.state = 'running') as avg_mem,\n\tmin((j.definition#>>'{resources,limits,memory}')::float) filter (where $__timeFilter(j.end_date) OR j.state = 'running') as min_mem,\n\tmax((j.definition#>>'{resources,limits,memory}')::float) filter (where $__timeFilter(j.end_date) OR j.state = 'running') as max_mem\nFROM\n\tjob j\n GROUP BY\n\tj.project_id) j_infos ON p.id = j_infos.project_id\nLEFT JOIN\n(SELECT project_id, count(user_id) as collabs FROM collaborator GROUP BY project_id) c_infos ON p.id = c_infos.project_id \n",
     "target": "project_list",
     "type": "table"
    }
   ]
  }
 ]
}