{{ if eq .Values.cluster.name "master" }}
apiVersion: batch/v1
kind: Job
metadata:
    name: infrabox-db-migration
    namespace: {{ template "system_namespace" . }}
spec:
    template:
        metadata:
            name: infrabox-db-migration
        spec:
            {{ include "imagePullSecret" . | indent 8 }}
            containers:
            {{ include "containers_database" . | indent 12 }}
            -
                name: migrate
                image: {{ include "image_repository" . }}/db:{{ include "image_tag" . }}
                env:
                {{ include "env_database" . | indent 16 }}
                {{ include "env_version" . | indent 16 }}
                -
                    name: INFRABOX_ADMIN_EMAIL
                    valueFrom:
                        secretKeyRef:
                            name: infrabox-admin
                            key: email
                -
                    name: INFRABOX_ADMIN_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: infrabox-admin
                            key: password
                volumeMounts:
                {{ include "mounts_rsa_public" . | indent 16 }}
                {{ include "mounts_rsa_private" . | indent 16 }}
            restartPolicy: OnFailure
            volumes:
                {{ include "volumes_database" . | indent 16 }}
                {{ include "volumes_rsa" . | indent 16 }}
{{ end }}
