apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ibpipelines.core.infrabox.net
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: core.infrabox.net
  names:
    kind: IBPipeline
    listKind: IBPipelineList
    plural: ibpipelines
    singular: ibpipline
  scope: Cluster
  version: v1alpha1
