{{ if .Values.image.private_repo }}
apiVersion: v1
kind: Secret
metadata:
  name: infrabox-docker-credentials
  namespace: {{ template "worker_namespace" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dockerCredentials" . }}
{{ end }}
