{
 "title": "Node Inspector",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_boot_time_seconds, instance)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_boot_time_seconds{instance=~\"$cluster.*\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$cluster:$node:.*\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Pod List",
   "type": "table",
   "description": "Pods of the inspected. NOT IMPLEMENTED YET",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$cluster:$node:.*\"} - node_boot_time_seconds{instance=~\"$cluster:$node:.*\"}"
    }
   ]
  },
  { "title": "Ressources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info. Values displayed are the average over the last 30s information.\n\nSpikes are therefore less likely to be identified, but also less reliable due to potential data loss.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"$cluster:$node:.*\"}[30s])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"$cluster:$node:.*\"}[30s])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"$cluster:$node:.*\"}[30s])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$cluster:$node:.*\"}[30s])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$cluster:$node:.*\"}[30s])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"$cluster:$node:.*\"}[30s])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$cluster:$node:.*\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$cluster:$node:.*\"} - node_memory_MemFree_bytes{instance=~\"$cluster:$node:.*\"} - (node_memory_Cached_bytes{instance=~\"$cluster:$node:.*\"} + node_memory_Buffers_bytes{instance=~\"$cluster:$node:.*\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$cluster:$node:.*\"} + node_memory_Buffers_bytes{instance=~\"$cluster:$node:.*\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$cluster:$node:.*\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$cluster:$node:.*\"} - node_memory_SwapFree_bytes{instance=~\"$cluster:$node:.*\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  }
 ]
}