apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: aksclusters.azure.service.infrabox.net
spec:
  group: azure.service.infrabox.net
  version: v1alpha1
  names:
    kind: AKSCluster
    listKind: AKSClusterList
    plural: aksclusters
    singular: akscluster
  scope: Namespaced
  validation:
    openAPIV3Schema:
      required:
      - spec
      properties:
        spec:
          required:
          - zone
          properties:
            diskSize:
              type: integer
              minimum: 10
            machineType:
              type: string
            numNodes:
              type: integer
              minimum: 1
            zone:
              type: string
            clusterVersion:
              type: string
