{{ if eq .Values.cluster.name "master" }}
{{ if .Values.gerrit.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: infrabox-gerrit-review
    namespace: {{ template "system_namespace" . }}
    labels:
        app: infrabox-gerrit-review
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: infrabox-gerrit-review
        spec:
            {{ include "imagePullSecret" . | indent 8 }}
            containers:
            {{ include "containers_database" . | indent 12 }}
            -
                name: gerrit-review
                image: {{ include "image_repository" . }}/gerrit-review:{{ include "image_tag"  . }}
                imagePullPolicy: Always
                env:
                {{ include "env_database" . | indent 16 }}
                {{ include "env_gerrit" . | indent 16 }}
                {{ include "env_general" . | indent 16 }}
                {{ include "env_version" . | indent 16 }}
                volumeMounts:
                {{ include "mounts_gerrit" . | indent 16 }}
            volumes:
                {{ include "volumes_database" . | indent 16 }}
                {{ include "volumes_gerrit" . | indent 16 }}
{{ end }}
{{ end }}
