FROM alpine:3.6

RUN apk add --no-cache \
    curl \
    bash \
    py2-pip \
    py2-cryptography \
    py2-jwt \
    py2-future \
    py2-psycopg2 \
    py2-flask \
    py2-pip && \
    pip install minio && \
    apk del py2-pip && \
    rm -rf /var/cache/apk/*

ENV HOME /
RUN curl https://sdk.cloud.google.com | bash
ENV PATH /google-cloud-sdk/bin:$PATH

COPY src/pyinfrabox/ /pyinfrabox
COPY src/job-api/server.py /server.py
COPY src/job-api/entrypoint.sh /entrypoint.sh
COPY src/pyinfraboxutils /pyinfraboxutils
COPY infrabox/test/utils/id_rsa.pub /var/run/secrets/infrabox.net/rsa/id_rsa.pub

ENV PYTHONPATH=/pyinfrabox:/

RUN adduser -S apiuser
USER apiuser

CMD /entrypoint.sh
